### ISSUE TITLE
port old raylib phong lighting stuff

### ISSUE THREAD

**Issue by redthing1** [redthing1/rengfx#8]
https://github.com/raysan5/raylib/commit/1bcb5ddd505e5c4bdac6f254e931e9c3145be88d
https://github.com/raysan5/raylib/commit/80eb4f3f50bb9773dd0e5d4b70c50e18df8996e5

**Comment by xdrie** [comment]
https://github.com/raysan5/raylib/blob/4b51248372302bd9f1baf2452b389f57f0173d59/examples/shaders_basic_lighting.c
https://github.com/raysan5/raylib/blob/4b51248372302bd9f1baf2452b389f57f0173d59/examples/resources/shaders/glsl330/phong.fs
https://github.com/raysan5/raylib/blob/4b51248372302bd9f1baf2452b389f57f0173d59/examples/resources/shaders/glsl330/phong.vs

**Comment by xdrie** [comment]
![Uploading image.png…]()
WIP!
