### ISSUE TITLE
showcase

### ISSUE THREAD

**Issue by redthing1** [redthing1/rengfx#9]
![unknown](https://user-images.githubusercontent.com/54390138/117510320-ba1a8500-af40-11eb-8c57-fec1d1869fb0.png)
![unknown](https://user-images.githubusercontent.com/54390138/117510330-bc7cdf00-af40-11eb-90a4-d3ca699b2f42.png)
![rengfx_fox(1)](https://user-images.githubusercontent.com/54390138/117510352-c9013780-af40-11eb-8101-aa7a3f7ac98c.gif)
![rec-2020-07-30_17 17 12(1)](https://user-images.githubusercontent.com/54390138/117510358-cb639180-af40-11eb-803b-283cdf596928.gif)

**Comment by xdrie** [comment]
![2021-01-01_01-22-09](https://user-images.githubusercontent.com/54390138/117608651-5bf1cb80-b113-11eb-8a9f-60bf095d578e.gif)

**Comment by xdrie** [comment]
![fast_slow_1620624652139-1_01](https://user-images.githubusercontent.com/54390138/117610747-1afbb600-b117-11eb-9ce4-ff594623284b.gif)
![2021-01-01_01-22-09](https://user-images.githubusercontent.com/54390138/117610827-3b2b7500-b117-11eb-95dc-011ea9185b6c.gif)

**Comment by xdrie** [comment]
![fast_slow_1620627214727](https://user-images.githubusercontent.com/54390138/117613890-66649300-b11c-11eb-90d3-15e15c79f34b.gif)

**Comment by xdrie** [comment]
![unknown-7](https://user-images.githubusercontent.com/54390138/117614323-03bfc700-b11d-11eb-8256-22a64b483ad7.png)
![unknown-6](https://user-images.githubusercontent.com/54390138/117614328-05898a80-b11d-11eb-8ee5-15efb22db842.png)
